In [1]:
import numpy as np

In [2]:
np.array([3,2,5,2,14,76,8,34])

array([ 3,  2,  5,  2, 14, 76,  8, 34])

In [3]:
np.array([3,2,5,2,14,76,8,34,4.5])

array([ 3. ,  2. ,  5. ,  2. , 14. , 76. ,  8. , 34. ,  4.5])

In [4]:
np.array([3,2,5,2,14,76,8,34,"hello"])

array(['3', '2', '5', '2', '14', '76', '8', '34', 'hello'], dtype='<U11')

In [5]:
np.array([3,2,5,2,14,76,8,34,True])

array([ 3,  2,  5,  2, 14, 76,  8, 34,  1])

In [6]:
np.array([[3,22,5,67], [4,2,6,8], [6,5,8,2]])

array([[ 3, 22,  5, 67],
       [ 4,  2,  6,  8],
       [ 6,  5,  8,  2]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [10]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5, dtype='int32')

array([1, 1, 1, 1, 1])

In [19]:
np.linspace(1,25, num=30, retstep=True)

(array([ 1.        ,  1.82758621,  2.65517241,  3.48275862,  4.31034483,
         5.13793103,  5.96551724,  6.79310345,  7.62068966,  8.44827586,
         9.27586207, 10.10344828, 10.93103448, 11.75862069, 12.5862069 ,
        13.4137931 , 14.24137931, 15.06896552, 15.89655172, 16.72413793,
        17.55172414, 18.37931034, 19.20689655, 20.03448276, 20.86206897,
        21.68965517, 22.51724138, 23.34482759, 24.17241379, 25.        ]),
 0.8275862068965517)