In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,50,24)

In [3]:
x

array([47, 18, 38, 46,  1,  3, 31, 30, 45, 12,  3, 26, 31, 17, 31, 16, 30,
       41, 25,  4, 43, 16, 19, 10])

In [4]:
np.sum(x)

583

In [6]:
x.sum()

583

In [7]:
np.max(x)

47

In [8]:
np.min(x)

1

In [10]:
np.mean(x)

24.291666666666668

In [11]:
np.var(x)

204.6232638888889

In [12]:
np.median(x)

25.5

In [13]:
np.std(x)

14.304658817633118

In [14]:
np.sort(x)

array([ 1,  3,  3,  4, 10, 12, 16, 16, 17, 18, 19, 25, 26, 30, 30, 31, 31,
       31, 38, 41, 43, 45, 46, 47])

In [15]:
# index of element
np.argmax(x)

0

In [16]:
# index of element
np.argmin(x)

4

In [17]:
# convert 1D to 2D
np.reshape(x, (4,6))

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10]])

In [18]:
np.reshape(x, (4,-1))

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10]])

In [19]:
np.reshape(x, (6,-1))

array([[47, 18, 38, 46],
       [ 1,  3, 31, 30],
       [45, 12,  3, 26],
       [31, 17, 31, 16],
       [30, 41, 25,  4],
       [43, 16, 19, 10]])

In [20]:
np.reshape(x, (-1,3))

array([[47, 18, 38],
       [46,  1,  3],
       [31, 30, 45],
       [12,  3, 26],
       [31, 17, 31],
       [16, 30, 41],
       [25,  4, 43],
       [16, 19, 10]])

In [21]:
x = np.reshape(x, (4,6))

In [22]:
x

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10]])

In [23]:
np.sum(x)

583

In [24]:
np.sum(x, axis=0)

array([134,  69, 157,  90,  53,  80])

In [25]:
np.sum(x, axis=1)

array([153, 147, 166, 117])

In [26]:
np.max(x, axis=0)

array([47, 30, 45, 46, 30, 41])

In [27]:
# convert NDimension to 1D
x.flatten()

array([47, 18, 38, 46,  1,  3, 31, 30, 45, 12,  3, 26, 31, 17, 31, 16, 30,
       41, 25,  4, 43, 16, 19, 10])

In [28]:
x

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10]])

In [29]:
# np.vstack
# np.hstack

In [30]:
x1 = np.array([[4,2,6,6,1,6]])
x2 = np.array([[56],[100],[59],[12]])

In [32]:
np.hstack((x, x2))

array([[ 47,  18,  38,  46,   1,   3,  56],
       [ 31,  30,  45,  12,   3,  26, 100],
       [ 31,  17,  31,  16,  30,  41,  59],
       [ 25,   4,  43,  16,  19,  10,  12]])

In [33]:
np.vstack((x, x1))

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10],
       [ 4,  2,  6,  6,  1,  6]])

In [34]:
np.r_[x, x1]

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10],
       [ 4,  2,  6,  6,  1,  6]])

In [35]:
np.c_[x, x2]

array([[ 47,  18,  38,  46,   1,   3,  56],
       [ 31,  30,  45,  12,   3,  26, 100],
       [ 31,  17,  31,  16,  30,  41,  59],
       [ 25,   4,  43,  16,  19,  10,  12]])

In [36]:
x

array([[47, 18, 38, 46,  1,  3],
       [31, 30, 45, 12,  3, 26],
       [31, 17, 31, 16, 30, 41],
       [25,  4, 43, 16, 19, 10]])

In [37]:
np.where(x < 10)

(array([0, 0, 1, 3], dtype=int64), array([4, 5, 4, 1], dtype=int64))

In [38]:
np.where(x < 10, x - 5, x)

array([[47, 18, 38, 46, -4, -2],
       [31, 30, 45, 12, -2, 26],
       [31, 17, 31, 16, 30, 41],
       [25, -1, 43, 16, 19, 10]])