In [1]:
import numpy as np

In [2]:
np.array([3,2,5,2,14,76,8,34])

array([ 3,  2,  5,  2, 14, 76,  8, 34])

In [3]:
np.array([3,2,5,2,14,76,8,34,4.5])

array([ 3. ,  2. ,  5. ,  2. , 14. , 76. ,  8. , 34. ,  4.5])

In [4]:
np.array([3,2,5,2,14,76,8,34,"hello"])

array(['3', '2', '5', '2', '14', '76', '8', '34', 'hello'], dtype='<U11')

In [5]:
np.array([3,2,5,2,14,76,8,34,True])

array([ 3,  2,  5,  2, 14, 76,  8, 34,  1])

In [6]:
np.array([[3,22,5,67], [4,2,6,8], [6,5,8,2]])

array([[ 3, 22,  5, 67],
       [ 4,  2,  6,  8],
       [ 6,  5,  8,  2]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [9]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(5, dtype='int32')

array([1, 1, 1, 1, 1])

In [15]:
np.linspace(1,25, num=30, retstep=True)

(array([ 1.        ,  1.82758621,  2.65517241,  3.48275862,  4.31034483,
         5.13793103,  5.96551724,  6.79310345,  7.62068966,  8.44827586,
         9.27586207, 10.10344828, 10.93103448, 11.75862069, 12.5862069 ,
        13.4137931 , 14.24137931, 15.06896552, 15.89655172, 16.72413793,
        17.55172414, 18.37931034, 19.20689655, 20.03448276, 20.86206897,
        21.68965517, 22.51724138, 23.34482759, 24.17241379, 25.        ]),
 0.8275862068965517)

In [18]:
# will generate random number b/w 0 and 1
np.random.random()

0.5042160974519365

In [19]:
np.random.random(5)

array([0.32872817, 0.07218009, 0.59010327, 0.7126587 , 0.65543578])

In [20]:
np.random.random((4,4))

array([[0.20990395, 0.79310229, 0.7045113 , 0.78011968],
       [0.21912451, 0.15922728, 0.08025612, 0.94763127],
       [0.40658073, 0.83854894, 0.75245744, 0.73478053],
       [0.00680396, 0.19200747, 0.39868059, 0.17910528]])

In [21]:
np.random.randn(4)

array([-1.08409698, -0.87041264, -0.18422061, -0.58155172])

In [22]:
np.random.randn(4,5)

array([[ 1.20974289,  0.73277802,  1.01687933,  0.02571208,  0.22574725],
       [ 0.42925236,  0.62216668,  1.33830453, -0.66597265, -0.37805009],
       [ 0.36068289,  1.71621919, -1.31789265, -1.96692525, -0.06228641],
       [-0.79094251, -0.20558857, -1.10508801, -0.99188349,  0.14282293]])

In [24]:
np.random.randint(1,25)

12

In [25]:
np.random.randint(1,25,10)

array([ 9,  2,  6,  6,  4, 17, 22, 10,  9, 23])

In [26]:
np.random.randint(1,25,(5,5))

array([[13, 12, 12, 23, 23],
       [20, 18, 14, 13,  6],
       [10,  8, 23, 10, 15],
       [24, 14, 19, 10, 20],
       [22,  1, 19, 20,  3]])

In [27]:
x = np.random.randint(1,50,20)

In [28]:
x

array([31,  2,  7, 11, 22, 41,  3, 43, 47,  4, 25, 40, 40, 38, 37, 22, 15,
       34, 21,  2])

In [29]:
np.shape(x)

(20,)

In [30]:
len(x)

20

In [31]:
x[0]

31

In [32]:
x[5]

41

In [33]:
x[-1]

2

In [34]:
x[0:5]

array([31,  2,  7, 11, 22])

In [35]:
x[10:0:-1]

array([25,  4, 47, 43,  3, 41, 22, 11,  7,  2])

In [36]:
x[::-1]

array([ 2, 21, 34, 15, 22, 37, 38, 40, 40, 25,  4, 47, 43,  3, 41, 22, 11,
        7,  2, 31])

In [37]:
x = np.random.randint(1,50,(4,6))

In [38]:
x

array([[35, 13, 15, 41, 32, 13],
       [ 4, 21,  9, 11, 47, 21],
       [31, 44, 43, 44, 25, 31],
       [40, 37, 16, 10, 39, 40]])

In [39]:
x.shape

(4, 6)

In [40]:
x[0]

array([35, 13, 15, 41, 32, 13])

In [44]:
x[0][0]

35

In [41]:
x[0:3]

array([[35, 13, 15, 41, 32, 13],
       [ 4, 21,  9, 11, 47, 21],
       [31, 44, 43, 44, 25, 31]])

In [42]:
x[:,2:4]

array([[15, 41],
       [ 9, 11],
       [43, 44],
       [16, 10]])

In [43]:
x[0:3,2:4]

array([[15, 41],
       [ 9, 11],
       [43, 44]])

In [45]:
x

array([[35, 13, 15, 41, 32, 13],
       [ 4, 21,  9, 11, 47, 21],
       [31, 44, 43, 44, 25, 31],
       [40, 37, 16, 10, 39, 40]])

In [46]:
x + 5

array([[40, 18, 20, 46, 37, 18],
       [ 9, 26, 14, 16, 52, 26],
       [36, 49, 48, 49, 30, 36],
       [45, 42, 21, 15, 44, 45]])

In [47]:
x - 6

array([[29,  7,  9, 35, 26,  7],
       [-2, 15,  3,  5, 41, 15],
       [25, 38, 37, 38, 19, 25],
       [34, 31, 10,  4, 33, 34]])

In [48]:
x = x + 5

In [49]:
x

array([[40, 18, 20, 46, 37, 18],
       [ 9, 26, 14, 16, 52, 26],
       [36, 49, 48, 49, 30, 36],
       [45, 42, 21, 15, 44, 45]])